export * from './cliente.repository';
export * from './factura-detalle.repository';
export * from './factura-detalleh.repository';
export * from './factura-encabezado.repository';
export * from './factura-encabezadoh.repository';
export * from './hogar.repository';
export * from './inventario.repository';
export * from './proveedor-conlista.repository';
export * from './proveedor-sinlista.repository';
